# Add this to: server.properties (on host)
# listeners=PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT2://:9094
# advertised.listeners=PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093,PLAINTEXT2://host.docker.internal:9094
# unstable.api.versions.enable=true
# group.coordinator.rebalance.protocols=classic,consumer,share

services:
  conduktor-console:
    image: conduktor/conduktor-console:1.34.0
    ports:
      - "8080:8080"
    volumes:
      - conduktor_data:/var/conduktor
    environment:
      CDK_DATABASE_URL: "postgresql://conduktor:change_me@postgresql:5432/conduktor-console"
      CDK_KAFKASQL_DATABASE_URL: "postgresql://conduktor:change_me@postgresql-sql:5432/conduktor-sql"
      CDK_ORGANIZATION_NAME: "local"
      CDK_CLUSTERS_0_ID: "local-kafka"
      CDK_CLUSTERS_0_NAME: "My Local Kafka"
      CDK_CLUSTERS_0_BOOTSTRAPSERVERS: "host.docker.internal:9092"  # adapt if needed
      CDK_CLUSTERS_0_COLOR: "#6A57C8"
      CDK_CLUSTERS_0_ICON: "kafka"
    depends_on:
      postgresql:
        condition: service_healthy
      postgresql-2:
        condition: service_healthy

  postgresql:
    image: postgres:14
    hostname: postgresql
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_DB: "conduktor-console"
      POSTGRES_USER: "conduktor"
      POSTGRES_PASSWORD: "change_me"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgresql-2:
    image: postgres:14
    hostname: postgresql-sql
    volumes:
      - pg_data_sql:/var/lib/postgresql/data
    environment:
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_DB: "conduktor-sql"
      POSTGRES_USER: "conduktor"
      POSTGRES_PASSWORD: "change_me"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  conduktor-monitoring:
    image: conduktor/conduktor-console-cortex:1.34.0
    environment:
      CDK_CONSOLE-URL: "http://conduktor-console:8080"

volumes:
  pg_data: {}
  pg_data_sql: {}
  conduktor_data: {}
